### PR TITLE
Backport modern players UUID's

### PR DESCRIPTION
**Pull request by js6pak**
* Implement Yggdrasil
* Implement backported uuid api's
Example use at https://github.com/js6pak/LuckPerms/tree/canyon

### CODE REVIEW

**Comment by js6pak** [comment]
I know `Server.java` have formatting issues again but I will fix them just before merge as they happen every time i open it with IDE

**Comment by astei** [comment]
Question: what kind of client mod would we need in order for a client to connect to a server with this patch in? I'm assuming it's a custom mod, since it looks like this goes through the [Minecraft modern login process](https://wiki.vg/Protocol_Encryption#Authentication).

**Comment by js6pak** [comment]
Im pretty sure same as before (I didn't tested it tho, because i always used yggdrasil in client mod and it worked). There is my b1.7.3 fabric mod that is doing that https://github.com/js6pak/mojangfix

**Comment by RhysB** [comment]
Pretty sure the following authentication systems are interconnected allowing the client to verify using the modern sessions API and the server to authenticate using the preYGGDRASIL methods.
`http://session.minecraft.net/game/joinserver.jsp?user=`
`https://sessionserver.mojang.com/session/minecraft/hasJoined?username=`
Most clientside patches work by just changing the `http://www.minecraft.net/game/joinserver.jsp?user=` URL to `http://session.minecraft.net/game/joinserver.jsp?user=`.

Canyon should consider allowing users to enable UUIDs even if the server is in offline mode. Many servers are looking at implementing hybrid authentication.
Having some kind of graceful UUID system would probably be best. The server could use the Mojang UUIDs for users who have one, otherwise it will generate and use an offline UUID like modern Minecraft Servers in offline mode using  `UUID offlineUUID = UUID.nameUUIDFromBytes(("OfflinePlayer:" + <playerName>).getBytes(Charsets.UTF_8));`

**Comment by js6pak** [comment]
This PR actually generate modern offline UUID in offline mode https://github.com/canyonmodded/canyon/pull/36/files#diff-e003d7399a66b05a28279bd68bc02b0bR150
Retrieving online UUIDs in offline mode should be done by plugins

**Comment by RhysB** [comment]
Canyon should still provide a cache and methods for getting Online UUIDs even in offline mode. Having 10+ plugins fetching UUIDs from Mojang isn't the best idea. Getting public servers to convert entirely to online mode isn't feasible causing servers to just implement UUIDs whenever possible to prevent issues when users change their username. I know using Mojang UUIDs in offline mode isn't ideal but in my opinion, it is the best course of action, especially with the new hybrid authentication solutions. This mode could be fully optional within the Canyon config.

**Comment by astei** [comment]
I think supporting hybrid authentication like @RhysB suggests is a good idea, but I don't think a blanket "online mode UUID even when offline mode" option makes sense. I think we should split the difference.

By default, Canyon works like post-1.7 release Minecraft does: offline mode gives you offline mode UUIDs and online mode gives you Mojang UUIDs. Like @RhysB suggests, we would also need a user cache to go along with this.

The part where we split the difference is that Canyon will add two events. One of them is invoked asynchronously and allows a plugin to fake the UUID of the player. The other event are invoked when a plugin attempts to look up a player by username, and allows plugins to set the UUID to use for the lookup.

This way, a plugin (which can be configured to fit the server owner's needs exactly) can handle UUID translation or accept Canyon's default behavior, which would be in line with modern Minecraft versions.

What do you think?

**Comment by js6pak** [comment]
Thats basically what i'm saying

**Comment by RhysB** [comment]
Sounds good :)

**Pull request closed without merging**
