### PR TITLE
Revert "Implemented inventory transaction event"

### PR DESCRIPTION
**Pull request by KoboDev**
_Reverts canyonmodded/canyon#67_

Code was found out to have added decompiled code from mcdev, that was not put through the importmcdev.sh script.
This will be fixed in a later date.

### CODE REVIEW

**Comment by Blayung** [comment]
Oh

**Comment by Blayung** [comment]
Well, I knew I'll fuck sth up.

**Comment by Blayung** [comment]
Does simply running `scripts/importmcdev.sh` fix it?

**Comment by KoboDev** [comment]
> Well, I knew I'll fuck sth up.

You can fix this by using the importmcdev script.

**Comment by Blayung** [comment]
@KoboDev #72

**Pull request merged**
